import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Careers at NanoFlows | Join Our AI Team",
  description: "Join NanoFlows AI Software Technologies and work on cutting-edge AI projects. We're hiring AI Engineers, Machine Learning specialists, and Automation experts. Build the future of AI with us.",
  keywords: [
    "AI careers",
    "AI jobs",
    "machine learning jobs",
    "AI engineer",
    "automation engineer",
    "AI company careers",
    "tech jobs",
    "NanoFlows careers",
    "AI developer jobs",
    "ML engineer positions",
    "deep learning jobs",
    "neural network engineer",
    "NLP engineer jobs",
    "natural language processing careers",
    "AI research jobs",
    "AI scientist positions",
    "data scientist AI",
    "AI analyst jobs",
    "AI architect positions",
    "AI solutions architect",
    "AI product manager",
    "AI project manager",
    "automation specialist",
    "RPA developer jobs",
    "chatbot developer",
    "conversational AI jobs",
    "AI software developer",
    "AI full stack developer",
    "AI backend developer",
    "AI frontend developer",
    "Python AI jobs",
    "TensorFlow jobs",
    "PyTorch careers",
    "AI startup jobs",
    "tech startup careers",
    "generative AI jobs",
    "LLM engineer",
    "prompt engineer jobs",
    "AI trainer positions",
    "AI operations engineer",
    "MLOps engineer",
    "AI infrastructure engineer",
    "cloud AI engineer",
    "AI DevOps",
    "AI QA engineer",
    "AI test engineer",
    "AI internships",
    "AI fresher jobs",
    "entry level AI jobs",
    "senior AI engineer",
    "lead AI engineer",
    "AI team lead",
    "AI director jobs",
    "VP AI positions",
    "remote AI jobs",
    "hybrid AI jobs",
    "AI jobs India",
    "AI jobs Vizag",
    "AI jobs Visakhapatnam",
    "software engineer AI",
  ],
  openGraph: {
    title: "Careers at NanoFlows | Join Our AI Team",
    description: "Join NanoFlows and work on cutting-edge AI projects. We're hiring AI Engineers, ML specialists, and Automation experts.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-services.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows Careers - Join Our AI Team",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Careers at NanoFlows | Join Our AI Team",
    description: "Work on cutting-edge AI projects. We're hiring AI Engineers, ML specialists, and Automation experts.",
    images: ["/og-services.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/careers",
  },
};
