import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cookie Policy | NanoFlows AI",
  description: "Read NanoFlows AI Software Technologies cookie policy. Learn how we use cookies and similar technologies on our website.",
  keywords: [
    "cookie policy",
    "NanoFlows cookies",
    "website cookies",
    "cookie usage",
    "cookie consent",
    "cookie preferences",
    "essential cookies",
    "analytics cookies",
    "functional cookies",
    "marketing cookies",
    "advertising cookies",
    "third party cookies",
    "first party cookies",
    "session cookies",
    "persistent cookies",
    "tracking cookies",
    "performance cookies",
    "preference cookies",
    "targeting cookies",
    "social media cookies",
    "cookie settings",
    "manage cookies",
    "delete cookies",
    "block cookies",
    "cookie opt out",
    "cookie control",
    "browser cookies",
    "local storage",
    "web storage",
    "tracking technologies",
    "pixel tracking",
    "web beacons",
    "clear GIFs",
    "fingerprinting",
    "device identification",
    "cookie duration",
    "cookie expiry",
    "cookie types",
    "cookie categories",
    "GDPR cookies",
    "cookie compliance",
    "ePrivacy",
    "cookie law",
    "cookie regulation",
    "cookie banner",
    "cookie notice",
    "cookie disclosure",
    "cookie information",
    "what are cookies",
    "how cookies work",
    "why we use cookies",
    "cookie purposes",
    "analytics tracking",
    "website analytics",
    "user experience cookies",
    "personalization cookies",
    "remember me cookies",
    "login cookies",
    "NanoFlows tracking",
  ],
  openGraph: {
    title: "Cookie Policy | NanoFlows AI",
    description: "Learn how NanoFlows uses cookies and similar technologies on our website.",
    type: "website",
    siteName: "NanoFlows",
  },
  twitter: {
    card: "summary",
    title: "Cookie Policy | NanoFlows AI",
    description: "Learn how NanoFlows uses cookies and similar technologies on our website.",
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/cookie-policy",
  },
};
