import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact Us | NanoFlows AI - Get in Touch",
  description: "Contact NanoFlows AI Software Technologies for AI solutions, automation services, and custom development inquiries. Reach out to our team for consultations and partnerships.",
  keywords: [
    "contact NanoFlows",
    "AI consultation",
    "AI services inquiry",
    "automation solutions contact",
    "AI development quote",
    "business inquiry",
    "partnership",
    "AI company contact",
    "get AI quote",
    "AI project inquiry",
    "custom AI development contact",
    "AI consulting contact",
    "enterprise AI inquiry",
    "AI implementation contact",
    "AI integration inquiry",
    "automation consultation",
    "business automation quote",
    "workflow automation inquiry",
    "chatbot development contact",
    "AI chatbot inquiry",
    "CRM AI contact",
    "AI CRM inquiry",
    "e-commerce AI contact",
    "AI solutions inquiry",
    "AI support contact",
    "technical support AI",
    "AI sales contact",
    "sales inquiry AI",
    "AI demo request",
    "product demo AI",
    "AI trial request",
    "free AI consultation",
    "AI expert contact",
    "speak to AI expert",
    "AI team contact",
    "NanoFlows email",
    "NanoFlows phone",
    "NanoFlows address",
    "NanoFlows location",
    "AI company Vizag",
    "AI company Visakhapatnam",
    "AI company India",
    "AI services India",
    "AI development India",
    "offshore AI development",
    "AI outsourcing contact",
    "AI vendor inquiry",
    "AI partner contact",
    "technology partner AI",
    "strategic partnership AI",
    "AI collaboration",
    "AI project proposal",
    "RFP AI services",
    "AI tender inquiry",
    "government AI contact",
    "enterprise inquiry AI",
    "startup AI contact",
    "SMB AI inquiry",
    "schedule AI meeting",
  ],
  openGraph: {
    title: "Contact Us | NanoFlows AI - Get in Touch",
    description: "Contact NanoFlows for AI solutions, automation services, and custom development inquiries.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-services.png",
        width: 1200,
        height: 630,
        alt: "Contact NanoFlows AI Software Technologies",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Us | NanoFlows AI",
    description: "Contact NanoFlows for AI solutions, automation services, and custom development inquiries.",
    images: ["/og-services.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/contact",
  },
};
