import type { Metadata } from "next";

export const homeMetadata: Metadata = {
  title: "NanoFlows | AI Software Technologies - Generative AI & Automation Solutions",
  description: "NanoFlows AI Software Technologies delivers cutting-edge Generative AI, Agentic AI systems, and business automation solutions. Transform your operations with custom AI development, intelligent chatbots, and enterprise automation.",
  keywords: [
    "AI software company",
    "generative AI solutions",
    "agentic AI development",
    "business automation",
    "AI integration",
    "machine learning services",
    "custom AI development",
    "AI consulting",
    "NanoFlows",
    "artificial intelligence company",
    "AI technology company",
    "AI solutions provider",
    "AI software development",
    "enterprise AI solutions",
    "AI transformation",
    "digital transformation AI",
    "intelligent automation",
    "smart business solutions",
    "AI-powered software",
    "next-gen AI",
    "cutting-edge AI",
    "advanced AI technology",
    "AI innovation",
    "AI research company",
    "AI development company",
    "custom LLM development",
    "large language models",
    "GPT integration",
    "ChatGPT solutions",
    "OpenAI integration",
    "AI chatbot company",
    "conversational AI",
    "voice AI solutions",
    "natural language AI",
    "NLP company",
    "AI agents development",
    "autonomous AI systems",
    "multi-agent AI",
    "AI orchestration",
    "workflow AI",
    "process automation AI",
    "RPA solutions",
    "robotic process automation",
    "cognitive automation",
    "AI analytics",
    "predictive AI",
    "AI insights",
    "data AI",
    "AI platforms",
    "SaaS AI",
    "cloud AI solutions",
    "AI as a service",
    "B2B AI company",
    "enterprise software AI",
    "AI startup",
    "AI company India",
    "AI company Vizag",
    "AI company Visakhapatnam",
    "best AI company",
    "top AI solutions",
    "AI automation vs human agents",
    "best manufacturing AI software",
    "AI for startups vs enterprise",
    "custom AI development services India",
    "top generative AI consulting",
    "autonomous sales agents platform",
    "AI CRM alternative",
    "business process automation AI"
  ],
  openGraph: {
    title: "NanoFlows | AI Software Technologies - Generative AI & Automation Solutions",
    description: "Transform your business with cutting-edge Generative AI, Agentic AI systems, and enterprise automation solutions.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-services.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows AI Software Technologies - Leading AI Solutions Provider",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "NanoFlows | AI Software Technologies",
    description: "Cutting-edge Generative AI, Agentic AI, and automation solutions for modern businesses.",
    images: ["/og-services.png"],
  },
  alternates: {
    canonical: "/",
  },
};
