import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | NanoFlows AI",
  description: "Read NanoFlows AI Software Technologies privacy policy. Learn how we collect, use, and protect your personal information when using our website and services.",
  keywords: [
    "privacy policy",
    "NanoFlows privacy",
    "data protection",
    "personal information",
    "data collection",
    "user privacy",
    "information security",
    "data privacy",
    "privacy terms",
    "data usage",
    "cookie policy",
    "GDPR compliance",
    "data protection policy",
    "privacy statement",
    "information collection",
    "personal data",
    "user data protection",
    "data handling",
    "privacy practices",
    "data security",
    "information privacy",
    "third party sharing",
    "data disclosure",
    "privacy rights",
    "user rights",
    "data subject rights",
    "opt out",
    "data deletion",
    "right to be forgotten",
    "data access",
    "privacy controls",
    "consent management",
    "data consent",
    "analytics privacy",
    "tracking privacy",
    "advertising privacy",
    "marketing privacy",
    "email privacy",
    "communication privacy",
    "contact data",
    "customer data",
    "client privacy",
    "business privacy",
    "B2B privacy",
    "AI data privacy",
    "machine learning privacy",
    "AI ethics privacy",
    "responsible AI",
    "transparent AI",
    "data governance",
    "compliance policy",
    "regulatory compliance",
    "privacy law",
    "data regulations",
    "NanoFlows data policy",
    "website privacy",
    "app privacy",
    "service privacy",
    "platform privacy",
  ],
  openGraph: {
    title: "Privacy Policy | NanoFlows AI",
    description: "Learn how NanoFlows collects, uses, and protects your personal information.",
    type: "website",
    siteName: "NanoFlows",
  },
  twitter: {
    card: "summary",
    title: "Privacy Policy | NanoFlows AI",
    description: "Learn how NanoFlows collects, uses, and protects your personal information.",
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/privacy-policy",
  },
};
