import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | NanoFlows AI",
  description: "Read NanoFlows AI Software Technologies terms of service. Understand the terms and conditions for using our website and AI services.",
  keywords: [
    "terms of service",
    "NanoFlows terms",
    "terms and conditions",
    "service agreement",
    "user agreement",
    "legal terms",
    "usage terms",
    "website terms",
    "platform terms",
    "service terms",
    "AI service terms",
    "software terms",
    "license terms",
    "subscription terms",
    "payment terms",
    "billing terms",
    "refund policy",
    "cancellation policy",
    "account terms",
    "user responsibilities",
    "acceptable use",
    "prohibited use",
    "content policy",
    "intellectual property",
    "copyright terms",
    "trademark terms",
    "proprietary rights",
    "ownership terms",
    "liability terms",
    "limitation of liability",
    "disclaimer",
    "warranty disclaimer",
    "indemnification",
    "dispute resolution",
    "arbitration clause",
    "governing law",
    "jurisdiction",
    "termination terms",
    "account termination",
    "service modification",
    "terms modification",
    "updates to terms",
    "notice requirements",
    "communication terms",
    "API terms",
    "integration terms",
    "third party terms",
    "partner terms",
    "affiliate terms",
    "reseller terms",
    "enterprise terms",
    "business terms",
    "commercial terms",
    "B2B agreement",
    "SaaS terms",
    "cloud service terms",
    "data terms",
    "privacy reference",
    "NanoFlows agreement",
  ],
  openGraph: {
    title: "Terms of Service | NanoFlows AI",
    description: "Terms and conditions for using NanoFlows website and AI services.",
    type: "website",
    siteName: "NanoFlows",
  },
  twitter: {
    card: "summary",
    title: "Terms of Service | NanoFlows AI",
    description: "Terms and conditions for using NanoFlows website and AI services.",
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/terms",
  },
};
