import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Products | NanoFlows - Autonomous AI Platforms",
  description: "Discover NanoFlows AI products: Lead Generation Engines, AI Calling Systems, Intelligent CRM & Dashboards, Content Marketing AI, and Internal Team Assistants. AI platforms that work autonomously.",
  keywords: [
    "AI products",
    "lead generation AI",
    "AI calling system",
    "intelligent CRM",
    "AI dashboard",
    "content marketing AI",
    "team assistants",
    "autonomous AI",
    "AI lead generation engine",
    "automated lead scoring",
    "AI prospecting tools",
    "multi-channel outreach AI",
    "CRM sync automation",
    "pipeline automation",
    "AI calling platform",
    "voice AI systems",
    "AI follow-up automation",
    "smart scheduling AI",
    "call transcription AI",
    "sentiment analysis AI",
    "AI CRM platform",
    "auto-updating CRM",
    "predictive CRM analytics",
    "real-time CRM insights",
    "custom CRM reporting",
    "zero data entry CRM",
    "AI content platform",
    "auto content generation",
    "SEO optimization AI",
    "multi-channel publishing",
    "content performance AI",
    "AI marketing automation",
    "internal AI assistants",
    "team productivity AI",
    "knowledge base AI",
    "onboarding automation AI",
    "internal workflow AI",
    "employee assistant AI",
    "autonomous business AI",
    "self-running AI systems",
    "24/7 AI automation",
    "AI SaaS products",
    "enterprise AI products",
    "business AI tools",
    "sales AI platform",
    "marketing AI platform",
    "operations AI platform",
    "AI productivity tools",
    "AI efficiency tools",
    "scalable AI solutions",
    "plug-and-play AI",
    "ready-to-use AI",
    "AI software products",
    "commercial AI platforms",
    "B2B AI products",
    "B2C AI solutions",
    "AI product suite",
    "integrated AI platform",
    "all-in-one AI solution",
    "AI business suite",
  ],
  openGraph: {
    title: "AI Products | NanoFlows - Autonomous AI Platforms",
    description: "AI platforms that work autonomously: Lead Generation, AI Calling, CRM & Dashboards, Content Marketing, and Team Assistants by NanoFlows.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-products.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows AI Products - Autonomous AI Platforms",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Products | NanoFlows",
    description: "AI platforms that work autonomously: Lead Generation, AI Calling, CRM & Dashboards, Content Marketing, and Team Assistants.",
    images: ["/og-products.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/products",
  },
};
