import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "AI Services | NanoFlows - Custom AI Solutions & Automation",
  description: "Explore NanoFlows comprehensive AI services including Custom LLM Systems, AI Automation, AI Agents & Chatbots, Business CRM Solutions, E-Commerce Platforms, and more. Transform your business with cutting-edge AI technology.",
  keywords: [
    "AI services",
    "custom LLM",
    "AI automation",
    "chatbots",
    "CRM solutions",
    "e-commerce platforms",
    "business automation",
    "machine learning",
    "AI development",
    "generative AI services",
    "agentic AI solutions",
    "custom AI development",
    "AI consulting services",
    "enterprise AI services",
    "AI integration services",
    "workflow automation",
    "process automation services",
    "intelligent automation",
    "AI chatbot development",
    "conversational AI",
    "natural language processing",
    "NLP services",
    "AI customer support",
    "AI sales automation",
    "marketing automation AI",
    "AI content generation",
    "AI data analytics",
    "predictive analytics services",
    "AI decision support",
    "business intelligence AI",
    "AI dashboard development",
    "real-time analytics",
    "AI reporting systems",
    "CRM AI integration",
    "sales CRM AI",
    "customer relationship AI",
    "AI lead generation",
    "lead scoring AI",
    "AI prospecting",
    "e-commerce AI",
    "AI product recommendations",
    "inventory AI management",
    "POS systems AI",
    "billing automation",
    "HRMS AI solutions",
    "payroll automation",
    "employee management AI",
    "appointment booking AI",
    "scheduling automation",
    "healthcare AI solutions",
    "clinic management AI",
    "hospital management systems",
    "gym management AI",
    "fitness software",
    "salon booking AI",
    "spa management systems",
    "legal case management AI",
    "lawyer software solutions",
    "courier management AI",
    "logistics automation",
    "WhatsApp CRM",
    "multi-channel AI",
    "omnichannel automation",
  ],
  openGraph: {
    title: "AI Services | NanoFlows - Custom AI Solutions & Automation",
    description: "Comprehensive AI services including Custom LLM Systems, AI Automation, Chatbots, CRM Solutions, and E-Commerce Platforms. Transform your business with NanoFlows.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-services.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows AI Services - Custom AI Solutions for Business",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Services | NanoFlows",
    description: "Comprehensive AI services including Custom LLM Systems, AI Automation, Chatbots, CRM Solutions, and E-Commerce Platforms.",
    images: ["/og-services.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/services",
  },
};
