import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Industries We Serve | NanoFlows - AI Solutions for Every Sector",
  description: "NanoFlows provides tailored AI solutions for Startups & SaaS, Enterprises, E-Commerce, Real Estate, Healthcare, Education, and Local Businesses. Industry-specific AI automation.",
  keywords: [
    "AI for startups",
    "enterprise AI",
    "e-commerce AI",
    "real estate AI",
    "healthcare AI",
    "education AI",
    "local business AI",
    "industry solutions",
    "SaaS AI solutions",
    "startup automation",
    "startup growth AI",
    "SaaS customer acquisition",
    "churn prediction AI",
    "product analytics AI",
    "enterprise automation",
    "digital transformation AI",
    "legacy system integration",
    "enterprise compliance AI",
    "global deployment AI",
    "process automation enterprise",
    "e-commerce automation",
    "personalized recommendations AI",
    "dynamic pricing AI",
    "inventory forecasting",
    "cart abandonment AI",
    "product recommendations",
    "review analysis AI",
    "real estate automation",
    "property matching AI",
    "lead nurturing real estate",
    "virtual property tours",
    "market analysis AI",
    "property valuation AI",
    "healthcare automation",
    "patient engagement AI",
    "medical record AI",
    "appointment scheduling healthcare",
    "diagnostic AI",
    "telemedicine AI",
    "education technology AI",
    "personalized learning AI",
    "student engagement AI",
    "EdTech automation",
    "learning management AI",
    "tutoring AI",
    "assessment AI",
    "local business automation",
    "small business AI",
    "SMB automation",
    "retail AI solutions",
    "restaurant AI",
    "hospitality AI",
    "service business AI",
    "professional services AI",
    "industry-specific AI",
    "vertical AI solutions",
    "sector-specific automation",
    "tailored AI platforms",
    "custom industry AI",
    "niche AI solutions",
  ],
  openGraph: {
    title: "Industries We Serve | NanoFlows - AI Solutions for Every Sector",
    description: "Tailored AI solutions for Startups, Enterprises, E-Commerce, Real Estate, Healthcare, Education, and Local Businesses by NanoFlows.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-industries.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows Industries - AI Solutions for Every Business Sector",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Industries We Serve | NanoFlows",
    description: "Tailored AI solutions for Startups, Enterprises, E-Commerce, Real Estate, Healthcare, Education, and Local Businesses.",
    images: ["/og-industries.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/industries",
  },
};
