import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog | NanoFlows AI - Insights on Generative AI & Automation",
  description: "Explore thought leadership articles on Generative AI, Agentic AI, automation systems, and AI for business growth. Stay updated with the latest AI trends and insights from NanoFlows.",
  keywords: [
    "AI blog",
    "generative AI articles",
    "agentic AI insights",
    "automation blog",
    "AI trends",
    "machine learning articles",
    "AI business insights",
    "tech blog",
    "AI thought leadership",
    "AI industry news",
    "AI research blog",
    "AI tutorials",
    "AI guides",
    "AI best practices",
    "AI case studies",
    "AI success stories",
    "AI implementation stories",
    "generative AI blog",
    "ChatGPT insights",
    "LLM articles",
    "large language models blog",
    "GPT technology",
    "AI writing",
    "AI content creation",
    "agentic systems blog",
    "autonomous AI articles",
    "AI agents blog",
    "multi-agent systems",
    "AI orchestration",
    "automation trends",
    "business automation blog",
    "workflow automation articles",
    "RPA insights",
    "intelligent automation blog",
    "AI for business blog",
    "enterprise AI articles",
    "AI ROI",
    "AI transformation",
    "digital transformation blog",
    "AI strategy articles",
    "AI innovation blog",
    "future of AI",
    "AI predictions",
    "AI technology trends",
    "emerging AI technologies",
    "AI ethics articles",
    "responsible AI",
    "AI governance",
    "AI regulation blog",
    "AI use cases",
    "AI applications blog",
    "industry AI insights",
    "sector AI articles",
    "AI solutions blog",
    "AI product updates",
    "NanoFlows news",
    "company AI blog",
    "AI expert articles",
    "AI opinion pieces",
  ],
  openGraph: {
    title: "Blog | NanoFlows AI - Insights on Generative AI & Automation",
    description: "Thought leadership on Generative AI, Agentic AI, automation systems, and AI for business growth.",
    type: "website",
    siteName: "NanoFlows",
    images: [
      {
        url: "/og-services.png",
        width: 1200,
        height: 630,
        alt: "NanoFlows Blog - AI Insights and Trends",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Blog | NanoFlows AI",
    description: "Thought leadership on Generative AI, Agentic AI, automation systems, and AI for business growth.",
    images: ["/og-services.png"],
  },
  robots: {
    index: true,
    follow: true,
  },
  alternates: {
    canonical: "/blog",
  },
};
